"""increase_telephone_length

Revision ID: 5f7d0ba00652
Revises: 87c86e2d54bc
Create Date: 2026-06-23 11:49:20.563314

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = '5f7d0ba00652'
down_revision: Union[str, None] = '87c86e2d54bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'telephone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'telephone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
