"""fix_score_minimum_float

Revision ID: 87c86e2d54bc
Revises: e5f2a9b1c7d3
Create Date: 2026-06-23 11:22:34.212613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87c86e2d54bc'
down_revision: Union[str, None] = 'e5f2a9b1c7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'score_minimum',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'score_minimum',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
