"""increase_campaign_status_length

Revision ID: 9103b0fc0774
Revises: 7b3e9c4f2a10
Create Date: 2026-06-17 16:40:26.529698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9103b0fc0774'
down_revision: Union[str, None] = '7b3e9c4f2a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
