"""add_score_minimum_to_campaigns

Revision ID: e84e2168d181
Revises: 
Create Date: 2026-06-11 13:42:44.749154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e84e2168d181'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('score_minimum', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'score_minimum')
    # ### end Alembic commands ###
